### PR TITLE
Contribution updated

### PR DESCRIPTION
**Pull request by monikabhardwaj**

### CODE REVIEW

**Review by mstuttgart — CHANGES_REQUESTED** [review]
@monikabhardwaj thanks for you PR. But this is wrong file.

This correct file is README.md

**Comment by mstuttgart** [comment]
@monikabhardwaj please, undo the CONTRIBUTING.md commit and resolve README conflicts

**Comment by monikabhardwaj** [comment]
Hi @mstuttgart i have reverted the changes.

**Review by mstuttgart — APPROVED** [review]

**Comment by mstuttgart** [comment]
I rebase you change and merge in master branch. Thanks :+1:

**Comment by monikabhardwaj** [comment]
Awesome.
Thanks.

**Pull request closed without merging**
