### PR TITLE
Add three movies to the list

### PR DESCRIPTION
**Pull request by spassarop**
- About Time
- Escape from the Planet of the Apes
- Déjà Vu

### CODE REVIEW

**Comment by spassarop** [comment]
About Time was already added in the meantime.

**Review by mstuttgart — APPROVED** [review]
@spassarop thanks :+1:

**Comment by spassarop** [comment]
@mstuttgart thanks to you :) I enjoy time travel movies, this collection will be great.

**Comment by mstuttgart** [comment]
@spassarop  yes :blush: Thanks again! :+1:

**Pull request merged**
